spring.application.name=travel-plan

# DB연동 세팅!
spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PW}

#JPA 핵심설정
#update
#Update the schema if necessary.
spring.jpa.hibernate.ddl-auto=update

# SQL 정렬
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG